import type { PlayData, NFLTeam } from "@/types/nfl"

export const NFL_TEAMS: NFLTeam[] = [
  {
    abbr: "ARI",
    name: "Arizona Cardinals",
    color: "97233F",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
  },
  { abbr: "ATL", name: "Atlanta Falcons", color: "A71930", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png" },
  { abbr: "BAL", name: "Baltimore Ravens", color: "241773", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png" },
  { abbr: "BUF", name: "Buffalo Bills", color: "00338D", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png" },
  {
    abbr: "CAR",
    name: "Carolina Panthers",
    color: "0085CA",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
  },
  { abbr: "CHI", name: "Chicago Bears", color: "0B162A", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png" },
  {
    abbr: "CIN",
    name: "Cincinnati Bengals",
    color: "FB4F14",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
  },
  { abbr: "CLE", name: "Cleveland Browns", color: "311D00", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png" },
  { abbr: "DAL", name: "Dallas Cowboys", color: "003594", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png" },
  { abbr: "DEN", name: "Denver Broncos", color: "FB4F14", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/den.png" },
  { abbr: "DET", name: "Detroit Lions", color: "0076B6", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/det.png" },
  { abbr: "GB", name: "Green Bay Packers", color: "203731", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png" },
  { abbr: "HOU", name: "Houston Texans", color: "03202F", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png" },
  {
    abbr: "IND",
    name: "Indianapolis Colts",
    color: "002C5F",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
  },
  {
    abbr: "JAX",
    name: "Jacksonville Jaguars",
    color: "006778",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
  },
  { abbr: "KC", name: "Kansas City Chiefs", color: "E31837", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png" },
  {
    abbr: "LAC",
    name: "Los Angeles Chargers",
    color: "0080C6",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
  },
  { abbr: "LAR", name: "Los Angeles Rams", color: "003594", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png" },
  { abbr: "LV", name: "Las Vegas Raiders", color: "000000", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png" },
  { abbr: "MIA", name: "Miami Dolphins", color: "008E97", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png" },
  {
    abbr: "MIN",
    name: "Minnesota Vikings",
    color: "4F2683",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
  },
  {
    abbr: "NE",
    name: "New England Patriots",
    color: "002244",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
  },
  { abbr: "NO", name: "New Orleans Saints", color: "D3BC8D", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/no.png" },
  { abbr: "NYG", name: "New York Giants", color: "0B2265", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png" },
  { abbr: "NYJ", name: "New York Jets", color: "125740", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png" },
  {
    abbr: "PHI",
    name: "Philadelphia Eagles",
    color: "004C54",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
  },
  {
    abbr: "PIT",
    name: "Pittsburgh Steelers",
    color: "FFB612",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
  },
  { abbr: "SEA", name: "Seattle Seahawks", color: "002244", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png" },
  {
    abbr: "SF",
    name: "San Francisco 49ers",
    color: "AA0000",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
  },
  {
    abbr: "TB",
    name: "Tampa Bay Buccaneers",
    color: "D50A0A",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
  },
  { abbr: "TEN", name: "Tennessee Titans", color: "0C2340", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png" },
  {
    abbr: "WAS",
    name: "Washington Commanders",
    color: "5A1414",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
  },
]

export const DEMO_PLAY: PlayData = {
  game_id: "demo_kc_sf_001",
  event_uid: "401547643",
  timestamp: new Date().toISOString(),
  source: "demo",
  down: 2,
  ydstogo: 7,
  yardline_100: 35,
  qtr: 4,
  half_seconds_remaining: 245,
  score_differential: -7,
  posteam: "KC",
  defteam: "SF",
  posteam_type: "away",
  goal_to_go: 0,
  home_team: "SF",
  away_team: "KC",
  home_score: 28,
  away_score: 21,
  status: {
    state: "in",
    period: 4,
    displayClock: "4:05",
    detail: "Q4 - 4:05",
    shortDetail: "Q4 4:05",
    completed: false,
  },
  situation: {
    down: 2,
    distance: 7,
    yardLine: 65,
    yardline_100: 35,
    possession: "KC",
    isRedZone: false,
    downDistanceText: "2nd & 7 at SF 35",
    shortDownDistanceText: "2nd & 7",
    possessionText: "KC has possession",
  },
  home_team_full: {
    id: "25",
    abbreviation: "SF",
    displayName: "San Francisco 49ers",
    name: "49ers",
    color: "AA0000",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    score: 28,
    homeAway: "home",
    records: { overall: "10-4", home: "5-2", away: "5-2" },
    leaders: {
      passing: {
        name: "Brock Purdy",
        shortName: "B. Purdy",
        displayName: "Brock Purdy",
        jersey: "13",
        position: "QB",
        headshot: "https://a.espncdn.com/i/headshots/nfl/players/full/4361741.png",
        displayValue: "312/456, 3758 YDS, 26 TD",
        playerId: "4361741",
        teamId: "25",
        value: 3758,
      },
      rushing: {
        name: "Christian McCaffrey",
        shortName: "C. McCaffrey",
        displayName: "Christian McCaffrey",
        jersey: "23",
        position: "RB",
        headshot: "https://a.espncdn.com/i/headshots/nfl/players/full/3117251.png",
        displayValue: "246 CAR, 1145 YDS, 13 TD",
        playerId: "3117251",
        teamId: "25",
        value: 1145,
      },
      receiving: {
        name: "Deebo Samuel",
        shortName: "D. Samuel",
        displayName: "Deebo Samuel",
        jersey: "19",
        position: "WR",
        headshot: "https://a.espncdn.com/i/headshots/nfl/players/full/3929630.png",
        displayValue: "62 REC, 892 YDS, 7 TD",
        playerId: "3929630",
        teamId: "25",
        value: 892,
      },
    },
  },
  away_team_full: {
    id: "12",
    abbreviation: "KC",
    displayName: "Kansas City Chiefs",
    name: "Chiefs",
    color: "E31837",
    logo: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    score: 21,
    homeAway: "away",
    records: { overall: "11-3", home: "6-1", away: "5-2" },
    leaders: {
      passing: {
        name: "Patrick Mahomes",
        shortName: "P. Mahomes",
        displayName: "Patrick Mahomes",
        jersey: "15",
        position: "QB",
        headshot: "https://a.espncdn.com/i/headshots/nfl/players/full/3139477.png",
        displayValue: "299/474, 3398 YDS, 22 TD",
        playerId: "3139477",
        teamId: "12",
        value: 3398,
      },
      rushing: {
        name: "Isiah Pacheco",
        shortName: "I. Pacheco",
        displayName: "Isiah Pacheco",
        jersey: "10",
        position: "RB",
        headshot: "https://a.espncdn.com/i/headshots/nfl/players/full/4361529.png",
        displayValue: "192 CAR, 824 YDS, 6 TD",
        playerId: "4361529",
        teamId: "12",
        value: 824,
      },
      receiving: {
        name: "Travis Kelce",
        shortName: "T. Kelce",
        displayName: "Travis Kelce",
        jersey: "87",
        position: "TE",
        headshot: "https://a.espncdn.com/i/headshots/nfl/players/full/15847.png",
        displayValue: "78 REC, 823 YDS, 4 TD",
        playerId: "15847",
        teamId: "12",
        value: 823,
      },
    },
  },
  weather: { temperature: 62, displayValue: "Partly Cloudy", gust: 8 },
  venue: {
    id: "3996",
    name: "Levi's Stadium",
    city: "Santa Clara",
    state: "CA",
    indoor: false,
    grass: true,
    capacity: 68500,
  },
  odds: {
    provider: "DraftKings",
    details: "KC -3.5",
    spread: -3.5,
    overUnder: 47.5,
    moneyline: { home: "+145", away: "-170" },
  },
  predictor: { homeWinProbability: 62.5, awayWinProbability: 37.5 },
  broadcasts: ["NBC", "Peacock"],
  lastPlay: {
    id: "401547643123",
    text: "Patrick Mahomes pass to Travis Kelce for 8 yards",
    type: "Pass",
    scoreValue: 0,
    team: "KC",
    athletesInvolved: ["3139477", "15847"],
  },
  event: {
    name: "Kansas City Chiefs at San Francisco 49ers",
    shortName: "KC @ SF",
    date: new Date().toISOString(),
    week: 15,
    seasonType: 2,
    seasonYear: 2024,
    neutralSite: false,
  },
  expected_points: 2.45,
  td_prob: 0.28,
  fg_prob: 0.35,
  no_score_prob: 0.32,
  opp_td_prob: 0.03,
  opp_fg_prob: 0.02,
  pass_probability: 0.72,
  run_probability: 0.28,
  predicted_play: "pass",
  pressure_probability: 0.35,
  pressure_risk: "medium",
}
